
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
# target 'VIA' do
#   # Pods for VIA
#   pod 'React', :path => '../node_modules/react-native/'
#   # pod 'React-Core', :path => '../node_modules/react-native'
#   # pod 'React-DevSupport', :path => '../node_modules/react-native/DevSupport'
#   pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
#   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#   # pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'


#   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

#   pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

#   pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

#   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#   pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'
#   pod 'RNSVG', :path => '../node_modules/react-native-svg'

#   pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

#   pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  

target 'VIA' do
    config = use_native_modules!
    def use_flipper!(versions = {})
  versions['Flipper'] ||= '~> 0.42'
  versions['Flipper-DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.2'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.1'
  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'
  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', :git => 'https://github.com/mikehardy/flipper', :branch => 'patch-1', :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['Flipper-DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', :podspec => 'https://raw.githubusercontent.com/mikehardy/flipper/patch-1/iOS/Podspecs/Flipper-Folly.podspec', :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end


    pod 'OpenSSL-Universal', '1.0.2.20'
    use_react_native!(:path => config["reactNativePath"])

  target 'VIATests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  # Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end
end



target 'VIA-tvOS' do
  # Pods for VIA-tvOS

  target 'VIA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
